/* notmuch.c generated by valac, the Vala compiler
 * generated from notmuch.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <notmuch.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_ADDRESS_MATCHER (address_matcher_get_type ())
#define ADDRESS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ADDRESS_MATCHER, AddressMatcher))
#define ADDRESS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ADDRESS_MATCHER, AddressMatcherClass))
#define IS_ADDRESS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ADDRESS_MATCHER))
#define IS_ADDRESS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ADDRESS_MATCHER))
#define ADDRESS_MATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ADDRESS_MATCHER, AddressMatcherClass))

typedef struct _AddressMatcher AddressMatcher;
typedef struct _AddressMatcherClass AddressMatcherClass;
typedef struct _AddressMatcherPrivate AddressMatcherPrivate;
#define _notmuch_database_close0(var) ((var == NULL) ? NULL : (var = (notmuch_database_close (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))

#define ADDRESS_MATCHER_TYPE_MAILADDRESS_FREQ (address_matcher_mailaddress_freq_get_type ())
typedef struct _AddressMatcherMailAddress_freq AddressMatcherMailAddress_freq;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_match_info_free0(var) ((var == NULL) ? NULL : (var = (g_match_info_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _address_matcher_mailaddress_freq_free0(var) ((var == NULL) ? NULL : (var = (address_matcher_mailaddress_freq_free (var), NULL)))
#define __g_slist_free_address_matcher_mailaddress_freq_free0(var) ((var == NULL) ? NULL : (var = (_g_slist_free_address_matcher_mailaddress_freq_free (var), NULL)))
typedef struct _ParamSpecAddressMatcher ParamSpecAddressMatcher;
#define _address_matcher_unref0(var) ((var == NULL) ? NULL : (var = (address_matcher_unref (var), NULL)))

struct _AddressMatcher {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AddressMatcherPrivate * priv;
};

struct _AddressMatcherClass {
	GTypeClass parent_class;
	void (*finalize) (AddressMatcher *self);
};

struct _AddressMatcherPrivate {
	notmuch_database_t* db;
	char* user_db_path;
	char* user_primary_email;
};

struct _AddressMatcherMailAddress_freq {
	char* address;
	guint occurances;
};

struct _ParamSpecAddressMatcher {
	GParamSpec parent_instance;
};


static gpointer address_matcher_parent_class = NULL;

gpointer address_matcher_ref (gpointer instance);
void address_matcher_unref (gpointer instance);
GParamSpec* param_spec_address_matcher (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_address_matcher (GValue* value, gpointer v_object);
void value_take_address_matcher (GValue* value, gpointer v_object);
gpointer value_get_address_matcher (const GValue* value);
GType address_matcher_get_type (void);
#define ADDRESS_MATCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ADDRESS_MATCHER, AddressMatcherPrivate))
enum  {
	ADDRESS_MATCHER_DUMMY_PROPERTY
};
AddressMatcher* address_matcher_new (void);
AddressMatcher* address_matcher_construct (GType object_type);
static GType address_matcher_mailaddress_freq_get_type (void) G_GNUC_UNUSED;
static AddressMatcherMailAddress_freq* address_matcher_mailaddress_freq_dup (const AddressMatcherMailAddress_freq* self);
static void address_matcher_mailaddress_freq_free (AddressMatcherMailAddress_freq* self);
static void address_matcher_mailaddress_freq_copy (const AddressMatcherMailAddress_freq* self, AddressMatcherMailAddress_freq* dest);
static void address_matcher_mailaddress_freq_destroy (AddressMatcherMailAddress_freq* self);
static gint address_matcher_revsort_by_freq (AddressMatcherMailAddress_freq* mail1, AddressMatcherMailAddress_freq* mail2);
static void _g_slist_free_address_matcher_mailaddress_freq_free (GSList* self);
void address_matcher_run (AddressMatcher* self, const char* name);
static void address_matcher_finalize (AddressMatcher* obj);
gint _vala_main (char** args, int args_length1);



#line 17 "notmuch.vala"
AddressMatcher* address_matcher_construct (GType object_type) {
#line 100 "notmuch.c"
	GError * _inner_error_;
	AddressMatcher* self;
	GKeyFile* config;
	char* home;
	_inner_error_ = NULL;
	self = (AddressMatcher*) g_type_create_instance (object_type);
#line 20 "notmuch.vala"
	config = g_key_file_new ();
#line 22 "notmuch.vala"
	home = g_strdup (g_getenv ("NOTMUCH_CONFIG"));
#line 23 "notmuch.vala"
	if (home == NULL) {
#line 113 "notmuch.c"
		char* _tmp0_;
#line 24 "notmuch.vala"
		home = (_tmp0_ = g_strdup (g_get_home_dir ()), _g_free0 (home), _tmp0_);
#line 117 "notmuch.c"
	}
	{
		char* _tmp1_;
		char* _tmp2_;
		char* _tmp3_;
#line 27 "notmuch.vala"
		g_key_file_load_from_file (config, _tmp1_ = g_strconcat (home, "/.notmuch-config", NULL), G_KEY_FILE_NONE, &_inner_error_);
#line 125 "notmuch.c"
		_g_free0 (_tmp1_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
#line 28 "notmuch.vala"
		_tmp2_ = g_key_file_get_string (config, "database", "path", &_inner_error_);
#line 132 "notmuch.c"
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
#line 28 "notmuch.vala"
		self->priv->user_db_path = (_tmp3_ = _tmp2_, _g_free0 (self->priv->user_db_path), _tmp3_);
#line 138 "notmuch.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * ex;
		ex = _inner_error_;
		_inner_error_ = NULL;
		{
			_g_error_free0 (ex);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_key_file_free0 (config);
		_g_free0 (home);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	{
		char* _tmp4_;
		char* _tmp5_;
#line 31 "notmuch.vala"
		_tmp4_ = g_key_file_get_string (config, "user", "primary_email", &_inner_error_);
#line 163 "notmuch.c"
		if (_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
#line 31 "notmuch.vala"
		self->priv->user_primary_email = (_tmp5_ = _tmp4_, _g_free0 (self->priv->user_primary_email), _tmp5_);
#line 169 "notmuch.c"
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError * ex;
		ex = _inner_error_;
		_inner_error_ = NULL;
		{
			_g_error_free0 (ex);
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		_g_key_file_free0 (config);
		_g_free0 (home);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_g_key_file_free0 (config);
	_g_free0 (home);
	return self;
}


#line 17 "notmuch.vala"
AddressMatcher* address_matcher_new (void) {
#line 17 "notmuch.vala"
	return address_matcher_construct (TYPE_ADDRESS_MATCHER);
#line 199 "notmuch.c"
}


#line 37 "notmuch.vala"
static gint address_matcher_revsort_by_freq (AddressMatcherMailAddress_freq* mail1, AddressMatcherMailAddress_freq* mail2) {
#line 205 "notmuch.c"
	gint result = 0;
#line 39 "notmuch.vala"
	if ((*mail1).occurances < (*mail2).occurances) {
#line 209 "notmuch.c"
		result = 1;
#line 39 "notmuch.vala"
		return result;
#line 213 "notmuch.c"
	} else {
#line 40 "notmuch.vala"
		if ((*mail1).occurances > (*mail2).occurances) {
#line 217 "notmuch.c"
			result = -1;
#line 40 "notmuch.vala"
			return result;
#line 221 "notmuch.c"
		} else {
			result = 0;
#line 41 "notmuch.vala"
			return result;
#line 226 "notmuch.c"
		}
	}
}


#line 922 "glib-2.0.vapi"
static char* string_strip (const char* self) {
#line 234 "notmuch.c"
	char* result = NULL;
	char* _result_;
#line 922 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 923 "glib-2.0.vapi"
	_result_ = g_strdup (self);
#line 924 "glib-2.0.vapi"
	g_strstrip (_result_);
#line 243 "notmuch.c"
	result = _result_;
#line 925 "glib-2.0.vapi"
	return result;
#line 247 "notmuch.c"
}


static gpointer _address_matcher_mailaddress_freq_dup0 (gpointer self) {
	return self ? address_matcher_mailaddress_freq_dup (self) : NULL;
}


static void _g_slist_free_address_matcher_mailaddress_freq_free (GSList* self) {
	g_slist_foreach (self, (GFunc) address_matcher_mailaddress_freq_free, NULL);
	g_slist_free (self);
}


#line 44 "notmuch.vala"
void address_matcher_run (AddressMatcher* self, const char* name) {
#line 264 "notmuch.c"
	GError * _inner_error_;
	notmuch_database_t* _tmp0_;
	GString* querystr;
	notmuch_query_t* q;
	notmuch_messages_t* msgs;
	GHashTable* ht;
	GRegex* re;
	GSList* addrs;
#line 44 "notmuch.vala"
	g_return_if_fail (self != NULL);
#line 275 "notmuch.c"
	_inner_error_ = NULL;
#line 46 "notmuch.vala"
	self->priv->db = (_tmp0_ = notmuch_database_open (self->priv->user_db_path, NOTMUCH_DATABASE_MODE_READ_ONLY), _notmuch_database_close0 (self->priv->db), _tmp0_);
#line 47 "notmuch.vala"
	querystr = g_string_new ("");
#line 48 "notmuch.vala"
	if (name != NULL) {
#line 283 "notmuch.c"
		char* _tmp2_;
		char* _tmp1_;
#line 49 "notmuch.vala"
		g_string_append (querystr, _tmp2_ = g_strconcat (_tmp1_ = g_strconcat ("to:", name, NULL), "*", NULL));
#line 288 "notmuch.c"
		_g_free0 (_tmp2_);
		_g_free0 (_tmp1_);
	}
#line 50 "notmuch.vala"
	if (self->priv->user_primary_email != NULL) {
#line 294 "notmuch.c"
		char* _tmp3_;
#line 51 "notmuch.vala"
		g_string_append (querystr, _tmp3_ = g_strconcat (" from:", self->priv->user_primary_email, NULL));
#line 298 "notmuch.c"
		_g_free0 (_tmp3_);
	}
#line 52 "notmuch.vala"
	g_debug ("notmuch.vala:52: %s", querystr->str);
#line 53 "notmuch.vala"
	q = notmuch_query_create (self->priv->db, querystr->str);
#line 54 "notmuch.vala"
	msgs = notmuch_query_search_messages (q);
#line 57 "notmuch.vala"
	ht = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
#line 59 "notmuch.vala"
	re = NULL;
#line 311 "notmuch.c"
	{
		GRegex* _tmp4_;
		GRegex* _tmp5_;
#line 63 "notmuch.vala"
		_tmp4_ = g_regex_new ("\\b\\w+([-+.]\\w+)*\\@\\w+[-\\.\\w]*\\.([-\\.\\w]+)*\\w\\b", G_REGEX_UNGREEDY, 0, &_inner_error_);
#line 317 "notmuch.c"
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch2_g_regex_error;
			}
			_g_string_free0 (querystr);
			_0 (q);
			_0 (msgs);
			_g_hash_table_unref0 (ht);
			_g_regex_unref0 (re);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
#line 63 "notmuch.vala"
		re = (_tmp5_ = _tmp4_, _g_regex_unref0 (re), _tmp5_);
#line 333 "notmuch.c"
	}
	goto __finally2;
	__catch2_g_regex_error:
	{
		GError * ex;
		ex = _inner_error_;
		_inner_error_ = NULL;
		{
			_g_error_free0 (ex);
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		_g_string_free0 (querystr);
		_0 (q);
		_0 (msgs);
		_g_hash_table_unref0 (ht);
		_g_regex_unref0 (re);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
#line 67 "notmuch.vala"
	while (TRUE) {
#line 358 "notmuch.c"
		GMatchInfo* matches;
		notmuch_message_t* msg;
		char* froms;
		GMatchInfo* _tmp8_;
		gboolean _tmp7_;
		GMatchInfo* _tmp6_ = NULL;
		gboolean found;
#line 67 "notmuch.vala"
		if (!notmuch_messages_valid (msgs)) {
#line 67 "notmuch.vala"
			break;
#line 370 "notmuch.c"
		}
		matches = NULL;
#line 69 "notmuch.vala"
		msg = notmuch_messages_get (msgs);
#line 70 "notmuch.vala"
		froms = g_strdup ((const char*) notmuch_message_get_header (msg, "to"));
#line 71 "notmuch.vala"
		found = (_tmp7_ = g_regex_match (re, froms, 0, &_tmp6_), matches = (_tmp8_ = _tmp6_, _g_match_info_free0 (matches), _tmp8_), _tmp7_);
#line 72 "notmuch.vala"
		while (TRUE) {
#line 381 "notmuch.c"
			char* from;
			char* _tmp9_;
			char* _tmp10_;
			guint occurs;
#line 72 "notmuch.vala"
			if (!found) {
#line 72 "notmuch.vala"
				break;
#line 390 "notmuch.c"
			}
#line 73 "notmuch.vala"
			from = g_match_info_fetch (matches, 0);
#line 74 "notmuch.vala"
			_tmp9_ = string_strip (from);
#line 396 "notmuch.c"
			_g_free0 (_tmp9_);
#line 75 "notmuch.vala"
			from = (_tmp10_ = g_utf8_strdown (from, -1), _g_free0 (from), _tmp10_);
#line 76 "notmuch.vala"
			occurs = GPOINTER_TO_UINT (g_hash_table_lookup (ht, from)) + 1;
#line 77 "notmuch.vala"
			g_hash_table_replace (ht, g_strdup (from), GUINT_TO_POINTER (occurs));
#line 404 "notmuch.c"
			{
				gboolean _tmp11_;
#line 78 "notmuch.vala"
				_tmp11_ = g_match_info_next (matches, &_inner_error_);
#line 409 "notmuch.c"
				if (_inner_error_ != NULL) {
					if (_inner_error_->domain == G_REGEX_ERROR) {
						goto __catch3_g_regex_error;
					}
					_g_free0 (from);
					_g_match_info_free0 (matches);
					_0 (msg);
					_g_free0 (froms);
					_g_string_free0 (querystr);
					_0 (q);
					_0 (msgs);
					_g_hash_table_unref0 (ht);
					_g_regex_unref0 (re);
					g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
#line 78 "notmuch.vala"
				found = _tmp11_;
#line 429 "notmuch.c"
			}
			goto __finally3;
			__catch3_g_regex_error:
			{
				GError * ex;
				ex = _inner_error_;
				_inner_error_ = NULL;
				{
					_g_error_free0 (ex);
				}
			}
			__finally3:
			if (_inner_error_ != NULL) {
				_g_free0 (from);
				_g_match_info_free0 (matches);
				_0 (msg);
				_g_free0 (froms);
				_g_string_free0 (querystr);
				_0 (q);
				_0 (msgs);
				_g_hash_table_unref0 (ht);
				_g_regex_unref0 (re);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			_g_free0 (from);
		}
#line 81 "notmuch.vala"
		notmuch_message_destroy (msg);
#line 82 "notmuch.vala"
		notmuch_messages_move_to_next (msgs);
#line 462 "notmuch.c"
		_g_match_info_free0 (matches);
		_0 (msg);
		_g_free0 (froms);
	}
#line 86 "notmuch.vala"
	addrs = NULL;
#line 469 "notmuch.c"
	{
		GList* addr_collection;
		GList* addr_it;
#line 87 "notmuch.vala"
		addr_collection = g_hash_table_get_keys (ht);
#line 475 "notmuch.c"
		for (addr_it = addr_collection; addr_it != NULL; addr_it = addr_it->next) {
			const char* addr;
#line 87 "notmuch.vala"
			addr = (const char*) addr_it->data;
#line 480 "notmuch.c"
			{
				AddressMatcherMailAddress_freq _tmp12_ = {0};
				AddressMatcherMailAddress_freq mail;
#line 88 "notmuch.vala"
				mail = (_tmp12_.address = g_strdup (addr), _tmp12_.occurances = GPOINTER_TO_UINT (g_hash_table_lookup (ht, addr)), _tmp12_);
#line 89 "notmuch.vala"
				addrs = g_slist_prepend (addrs, _address_matcher_mailaddress_freq_dup0 (&mail));
#line 488 "notmuch.c"
				address_matcher_mailaddress_freq_destroy (&mail);
			}
		}
#line 87 "notmuch.vala"
		_g_list_free0 (addr_collection);
#line 494 "notmuch.c"
	}
#line 93 "notmuch.vala"
	addrs = g_slist_sort (addrs, (GCompareFunc) address_matcher_revsort_by_freq);
#line 498 "notmuch.c"
	{
		GSList* a_collection;
		GSList* a_it;
#line 96 "notmuch.vala"
		a_collection = addrs;
#line 504 "notmuch.c"
		for (a_it = a_collection; a_it != NULL; a_it = a_it->next) {
			AddressMatcherMailAddress_freq* a;
#line 96 "notmuch.vala"
			a = _address_matcher_mailaddress_freq_dup0 ((AddressMatcherMailAddress_freq*) a_it->data);
#line 509 "notmuch.c"
			{
				char* from;
#line 97 "notmuch.vala"
				from = g_strdup ((*a).address);
#line 98 "notmuch.vala"
				fprintf (stdout, "%s %d\n", from, (gint) (*a).occurances);
#line 516 "notmuch.c"
				_address_matcher_mailaddress_freq_free0 (a);
				_g_free0 (from);
			}
		}
	}
	_g_string_free0 (querystr);
	_0 (q);
	_0 (msgs);
	_g_hash_table_unref0 (ht);
	_g_regex_unref0 (re);
	__g_slist_free_address_matcher_mailaddress_freq_free0 (addrs);
}


static void address_matcher_mailaddress_freq_copy (const AddressMatcherMailAddress_freq* self, AddressMatcherMailAddress_freq* dest) {
	dest->address = g_strdup (self->address);
	dest->occurances = self->occurances;
}


static void address_matcher_mailaddress_freq_destroy (AddressMatcherMailAddress_freq* self) {
	_g_free0 (self->address);
}


static AddressMatcherMailAddress_freq* address_matcher_mailaddress_freq_dup (const AddressMatcherMailAddress_freq* self) {
	AddressMatcherMailAddress_freq* dup;
	dup = g_new0 (AddressMatcherMailAddress_freq, 1);
	address_matcher_mailaddress_freq_copy (self, dup);
	return dup;
}


static void address_matcher_mailaddress_freq_free (AddressMatcherMailAddress_freq* self) {
	address_matcher_mailaddress_freq_destroy (self);
	g_free (self);
}


static GType address_matcher_mailaddress_freq_get_type (void) {
	static volatile gsize address_matcher_mailaddress_freq_type_id__volatile = 0;
	if (g_once_init_enter (&address_matcher_mailaddress_freq_type_id__volatile)) {
		GType address_matcher_mailaddress_freq_type_id;
		address_matcher_mailaddress_freq_type_id = g_boxed_type_register_static ("AddressMatcherMailAddress_freq", (GBoxedCopyFunc) address_matcher_mailaddress_freq_dup, (GBoxedFreeFunc) address_matcher_mailaddress_freq_free);
		g_once_init_leave (&address_matcher_mailaddress_freq_type_id__volatile, address_matcher_mailaddress_freq_type_id);
	}
	return address_matcher_mailaddress_freq_type_id__volatile;
}


static void value_address_matcher_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_address_matcher_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		address_matcher_unref (value->data[0].v_pointer);
	}
}


static void value_address_matcher_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = address_matcher_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_address_matcher_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_address_matcher_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		AddressMatcher* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = address_matcher_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_address_matcher_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	AddressMatcher** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = address_matcher_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_address_matcher (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecAddressMatcher* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_ADDRESS_MATCHER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_address_matcher (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ADDRESS_MATCHER), NULL);
	return value->data[0].v_pointer;
}


void value_set_address_matcher (GValue* value, gpointer v_object) {
	AddressMatcher* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ADDRESS_MATCHER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ADDRESS_MATCHER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		address_matcher_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		address_matcher_unref (old);
	}
}


void value_take_address_matcher (GValue* value, gpointer v_object) {
	AddressMatcher* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_ADDRESS_MATCHER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_ADDRESS_MATCHER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		address_matcher_unref (old);
	}
}


static void address_matcher_class_init (AddressMatcherClass * klass) {
	address_matcher_parent_class = g_type_class_peek_parent (klass);
	ADDRESS_MATCHER_CLASS (klass)->finalize = address_matcher_finalize;
	g_type_class_add_private (klass, sizeof (AddressMatcherPrivate));
}


static void address_matcher_instance_init (AddressMatcher * self) {
	self->priv = ADDRESS_MATCHER_GET_PRIVATE (self);
	self->priv->user_db_path = NULL;
	self->priv->user_primary_email = NULL;
	self->ref_count = 1;
}


static void address_matcher_finalize (AddressMatcher* obj) {
	AddressMatcher * self;
	self = ADDRESS_MATCHER (obj);
	_notmuch_database_close0 (self->priv->db);
	_g_free0 (self->priv->user_db_path);
	_g_free0 (self->priv->user_primary_email);
}


GType address_matcher_get_type (void) {
	static volatile gsize address_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&address_matcher_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_address_matcher_init, value_address_matcher_free_value, value_address_matcher_copy_value, value_address_matcher_peek_pointer, "p", value_address_matcher_collect_value, "p", value_address_matcher_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (AddressMatcherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) address_matcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AddressMatcher), 0, (GInstanceInitFunc) address_matcher_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType address_matcher_type_id;
		address_matcher_type_id = g_type_register_fundamental (g_type_fundamental_next (), "AddressMatcher", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&address_matcher_type_id__volatile, address_matcher_type_id);
	}
	return address_matcher_type_id__volatile;
}


gpointer address_matcher_ref (gpointer instance) {
	AddressMatcher* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void address_matcher_unref (gpointer instance) {
	AddressMatcher* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		ADDRESS_MATCHER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


#line 103 "notmuch.vala"
gint _vala_main (char** args, int args_length1) {
#line 735 "notmuch.c"
	gint result = 0;
	AddressMatcher* app;
#line 104 "notmuch.vala"
	app = address_matcher_new ();
#line 105 "notmuch.vala"
	address_matcher_run (app, args[1]);
#line 742 "notmuch.c"
	result = 0;
	_address_matcher_unref0 (app);
#line 106 "notmuch.vala"
	return result;
#line 747 "notmuch.c"
}


#line 103 "notmuch.vala"
int main (int argc, char ** argv) {
#line 103 "notmuch.vala"
	g_type_init ();
#line 103 "notmuch.vala"
	return _vala_main (argv, argc);
#line 757 "notmuch.c"
}




